name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read
jobs:
  build:
    env:
      CI: "true"
      BUNDLE_GEMFILE: gemfiles/${{ matrix.appraisal }}.gemfile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ "3.4.2", "3.3.7", "3.2.8" ]
        appraisal: ["latest", "old", "older", "the_oldest"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec appraisal ${{ matrix.appraisal }} rspec -f j -o tmp/rspec_results.json -f p
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Publish RSpec Report
        uses: SonicGarden/rspec-report-action@v6
        with:
          json-path: tmp/rspec_results.json
        if: always()
      - name: Publish to Coveralls
        uses: coverallsapp/github-action@v2
