name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.4.2", "3.3.7", "3.2.8"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run RSpec
      run: bundle exec rspec -f j -o tmp/rspec_results.json -f p
    - name: Run rubocop
      run: bundle exec rubocop
    - name: Publish RSpec Report
      uses: SonicGarden/rspec-report-action@v6
      with:
        json-path: tmp/rspec_results.json
      if: always()
